version: "3.1"
services:

    mysql:
      build:
        context: .
        dockerfile: docker/mysql/Dockerfile
      container_name: godel-php-k8s-demo-mysql
      command: --default-authentication-plugin=mysql_native_password
      working_dir: /application
      volumes:
        - .:/application
        - ./.mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=42
        - MYSQL_DATABASE=godel-k8s-demo
        - MYSQL_USER=godel-k8s-demo
        - MYSQL_PASSWORD=42
      ports:
        - "8486:3306"

    webserver:
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
      container_name: godel-php-k8s-demo-webserver
      working_dir: /application
      depends_on:
        - php-fpm
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8484:80"

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: godel-php-k8s-demo-php-fpm
      depends_on:
        - mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

