apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-fpm
  name: php-fpm
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: php-fpm